### ISSUE TITLE
Generic/wrong application icons for RV Player

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#27]
**How to duplicate**
Install new Player

![screen shot 2015-12-18 at 6 00 40 pm copy](https://cloud.githubusercontent.com/assets/5868781/11915597/5409de24-a67b-11e5-921c-fbdc8192b451.png)
![screen-shot-2015-12-18-at-6 04 06-pm](https://cloud.githubusercontent.com/assets/5868781/11915598/54117b84-a67b-11e5-9d51-1130a1fa67ad.png)

**Expected outcome**
RV icons on Start options

**Environment**
Win 10 32bit

**Comment by tejohnso** [comment]
@ByronDarlison Can we close this and consider for a future enhancement?
@fjvallarino FYI

**Comment by ByronDarlison** [comment]
@fjvallarino I thought something had come up about this and you had already replaced these? 

@tejohnso @fjvallarino do we have icons for these apps already? And if we do, can you post them here for review?

And, how difficult is it to update these?

Thanks!

**Comment by fjvallarino** [comment]
@ByronDarlison @tejohnso No, what I changed was the icon of the installer itself; it's now using the same icon the old installer uses (Rise's logo). I'm not sure which icon we should use for this. Since we're not specifying anything, it uses the default icons for that type of file. I guess using the Rise icon for Stop and Uninstall is ok, but I'm not sure about the Edit one, since we're actually opening the file for edition with Notepad.

**Comment by ByronDarlison** [comment]
@lapinnoir could you list out all of our apps and their associated icons for both Windows and Ubuntu in a doc and let's review there and work out next steps. Thanks!

**Comment by lapinnoir** [comment]
@ByronDarlison added as a checklist in https://trello.com/c/AFtIspbm/1093-3-rise-player-new-installer-testing - new card?

**Comment by ByronDarlison** [comment]
@lapinnoir that's fine. Thanks
