### ISSUE TITLE
BigQuery Not Registering Display on Initial Install

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#52]
**How to duplicate**
Fulfill 360#artifacts installation to inputting the Display ID (valid).
Run the Display with this valid ID.
Edit the Display ID, save and reboot.
Notice the invalid Display ID message on reboot.
Run BQ.

The valid Display ID does not show (3BMRU7DZWJ6E) in any of the queries.
The invalid Display ID shows (3BMRU7DZWJ6EEEE) in BQ.

**Environment**
Win 8 32bit

**Expected outcome**
I imagine that the initial Display ID that a person adds after installing it should show on BQ.
I had some Display IDs used in testing show on BQ and others not show on BQ.

**Scenario**
I was testing three OS (Linux 14.04, 15.10, Win 10) this morning to adding their Display ID and left the Display running.  I noticed that their ID was not showing on BQ.
I was doing another test for Win 8 32bit and noticed on BQ that the invalid DisplayID only showed (see http://recordit.co/1EvtBfbzyx relating to another test for the Edit Display ID option)

**Comment by tejohnso** [comment]
@lapinnoir The install process is complete by the time you enter the valid display id.  There's nothing left for the installer to log because at that point it's the viewer and the player acting.

Once you change to an invalid display id and reboot, then installer then runs again (after reboot) and so it will log events with the invalid display id.

You'd find the valid display id in the player events table but not installer.  I think that's out of scope for this testing though.  

Also not that we will eventually be bringing the display id configuration into the installer so this situation will eventually work as you expected it to :)
