### ISSUE TITLE
Add pop up "Restarting Rise Vision Player" when selecting Restart

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#54]
**How to Duplicate**
Install 356#artifacts
Select Restart command
See 15.10 (http://g.recordit.co/Q4WNqzv8Rt.gif) 

Expected
Add pop up "Restarting Rise Vision Player" when selecting Restart

Environment
Ubuntu 14.04 and 15.10 64bit

(submitted as new issue, previously combined in somewhat related issue https://github.com/Rise-Vision/rise-launcher/issues/50)

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso I'll use this issue to reach an agreement on how we should handle this notifications (since it affects issue #50 too). Currently we have three menu options displaying bubbles (uninstall, restart, stop), and all of them display a bubble at the beginning and at the end. Both of these bubbles last for about 10 seconds, a duration which cannot be changed. Should we display only one bubble for all of them? Should that bubble be the one indicating the action being performed, or the one indicating it actually finished?

**Comment by tejohnso** [comment]
My suggestions:
For restarting we can show a restarting bubble.  We don't need a finished bubble because the user will see the viewer pop up.

For uninstall, show the bubble upon completion since it should complete fairly quickly.

For stop, show only "stopping player" when the process begins.

**Comment by lapinnoir** [comment]
@tejohnso I agree with those suggestions.

**Comment by ByronDarlison** [comment]
@fjvallarino reviewed with @robb-price are you okay with taking it as @tejohnso described above? Thanks

**Comment by fjvallarino** [comment]
@ByronDarlison @robb-price @lapinnoir This is implemented in these artifacts: https://circleci.com/gh/Rise-Vision/rise-launcher-electron/383#artifacts

**Comment by robb-price** [comment]
@fjvallarino Thanks.

@lapinnoir Can you test the installer on all appropriate OS' and let us know if this passes?

Thanks!

**Comment by lapinnoir** [comment]
@fjvallarino The Restart option and the pop up appears on Linux 14.04 and 15.10, closing issue.
