### ISSUE TITLE
Message "Error setting file permissions" in log for both Linux and Windows

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher#63]
**How it works now**
1. Run the new Installer on Ubuntu 14.04, Ubuntu 15.5, Win 7 and Win 10. Notice that you get the message: An unknown error has occurred.  Please try again or post a question to http://community.risevision.com

**In installer-detail.log**
It states
````
message: 'Error setting file permissions',
error:
Error: ENOENT: no such file or directory, chmod '/home/hs/rvplayer/Installer/installer''

```

Logfiles: 

Win 7:
https://uploads.intercomcdn.com/i/o/3737804/d8c02925b79c5d06f6b5af9b/installer-detail.log
https://uploads.intercomcdn.com/i/o/3737805/a2f2931b9259dca0d58f4d63/installer-events.log

Win 10:
https://uploads.intercomcdn.com/i/o/3737344/0ab762242e0f48e8a910a066/installer-detail.log
https://uploads.intercomcdn.com/i/o/3737345/12cd909451a7f112b1178951/installer-events.log


**How it should work**
Have a clearer error message for the user.  
Unfortunately I don't know why there is 'Error setting file permissions'

**Comment by tejohnso** [comment]
@fjvallarino I don't think we need to reject on this error.

**Comment by fjvallarino** [comment]
@lapinnoir I just tried installing *current* installer, then installing *new* installer on top and did not have issues. Is there anything else I should consider when testing this?

@tejohnso I'm not sure in which context that error happened, but if we can't set the execution flag on installer we may not be able to run it.

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino 

I think the source of the file permission error is that it’s ‘in use’ because the using is exiting (via Ctrl+W) only..

Scenario: the user will try to install, but the rvplayer folder from previous Installer is not deleted. In this case the user is not aware that they should delete the rvplayer folder (which is how they uninstall the old player)

Improvement would be: Instead of seeing the ‘unknown’ error message the user sees that they need to delete the rvplayer / previous install first.  I think that this is similar to the CAP error message that the user sees when they have CAP installed and they are not aware that they need to uninstall CAP.

This error comes up when the following happens (any arch):

Run through rvplayer-installer.sh
Select **no to startup**
**Don’t input DisplayID** and select quit 
Install installer-lnx-64.sh

Run through rvplayer-installer.sh
Select **yes to startup**
**Don’t input DisplayID**, select quit
Install installer-lnx-32.sh

Run through rvplayer-installer.sh
Select **yes to startup**
**Add Display ID** then quit
(wait for some time) then Ctrl+W out of Player
Install installer-lnx-64.sh

Run through rvplayer-installer.sh
Select **no to startup**
**Add Display ID** then quit
(wait for some time) then Ctrl+W out of Player
Install installer-lnx-64.sh

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino I saw the same error message and log come up on a Win 10 box...haven't gone through steps to replicate environment.

**Comment by robb-price** [comment]
@lapinnoir If it occurs on Windows 10 as well, can you update the original description to include the relevant OS's it occurs on? Also @lapinnoir @tejohnso @fjvallarino  why is this an "enhancement"? It sounds like when this happens, the user can't proceed, and doesn't have a clear understanding of what to do next. I'd call that a bug. Am I misunderstanding?

@lapinnoir For all issues/enhancements, can you make sure to arrange them in 

<b>How it works now:</b>
XX
<b>How it should work:</b>
XX
I want to keep that same format on all issues we log.

**Comment by lapinnoir** [comment]
@robb-price With Windows 10, I am going to log when I am able to duplicate again but I want to simplify it and only have one issue for Linux and then open a new issue for Windows

**Comment by lapinnoir** [comment]
@robb-price I labeled as enhancement because it's improving on an error message from "unknown error" to known but I'll switch to bug.

**Comment by robb-price** [comment]
@lapinnoir Can you take a look at the changes I made to the description here: https://github.com/Rise-Vision/rise-launcher/issues/62, and apply that same idea here? We need to make sure the Dev team clearly understands what the current problem is, and what we expect to happen.

Remember, think of this ALL from the User perspective.

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/1754044009

**Comment by lapinnoir** [comment]
@robb-price I think the issue is updated now. I've also included in the issue that the error is seen on Win 10. But I have come across the 'Error setting file permissions' for both Ubuntu and Windows and this happens even when I delete the rvplayer folder.  I am not sure what else is contributing to this.

FYI @tejohnso @fjvallarino this was reported also in the Community and the user has posted a workaround that worked for him: https://community.risevision.com/rise_vision_inc/topics/rise-player-installation-an-unknown-error-has-occurred

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino In addition, the user has mentioned (and sent through additional logs) for this occurring on Win 7 - **on Win 7 they don't have any of the Rise Player installed before on this machine**. I will amend the issue with this new info.

**Comment by tejohnso** [comment]
@lapinnoir Are you going to add links to the log files here?

**Comment by lapinnoir** [comment]
@tejohnso 

Win 7:
https://uploads.intercomcdn.com/i/o/3737804/d8c02925b79c5d06f6b5af9b/installer-detail.log
https://uploads.intercomcdn.com/i/o/3737805/a2f2931b9259dca0d58f4d63/installer-events.log

Win 10:
https://uploads.intercomcdn.com/i/o/3737344/0ab762242e0f48e8a910a066/installer-detail.log
https://uploads.intercomcdn.com/i/o/3737345/12cd909451a7f112b1178951/installer-events.log

I'll update the issue

**Comment by tejohnso** [comment]
@hcs0 I went through what I think is the most likely way to replicate this and I couldn't.  I downloaded the old installer, installed it, used CTRL-W to close viewer, then downloaded the new installer and ran it.  All worked well. Can you confirm this is still an issue?

**Comment by hcs0** [comment]
@tejohnso I get this error message (in the logs) since I am constantly uninstalling/reinstalling the Player for testing so it may be because of residue files left in rvplayer that Blake noticed earlier with the carts.
The logs that I've sent through last week (https://github.com/Rise-Vision/rise-launcher/issues/63#issuecomment-173029544) was from another user so I've asked him if he could try again but to completely clear out all the files to see if that makes a difference.  I looked at his Displays and they are still offline/last connection since he reported this issue.

Thanks!

**Comment by hcs0** [comment]
Issue can't be recreated easily even though it has come up via tests and also at least one user.
